config/routes.rb
Rails.application.routes.draw do

  root 'users/homes#top'
  devise_for :users, only: [:session, :registration]
  devise_for :admins, only: :session

  scope module: :users do
    delete "notifications" => "notifications#destroy_all"
    resources :notifications, only: [:index, :destroy]
    get 'homes/about'
    resources :users, only: [:show, :edit, :update, :destroy] do
      post 'follow/:id' => 'relationships#follow', as: 'follow'
      post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
      member do
        get :retire, :follow, :follower
      end
    end
    resources :photos, only: [:index, :new, :create, :show, :destroy, :update] do
      member do
        get :likes, :comments
      end
      resources :comments, only: [:create, :destroy, :update]
      resource :likes, only: [:create, :destroy]
    end
    resource :contacts, only: [:new, :create]
    get 'contacts/done' => "contacts#done"
  end


  namespace :admins do
    get 'home/top'
    resources :users, only: [:index, :show, :destroy]
    resources :photos, only: [:index, :show, :destroy]
    delete "contacts" => "contacts#destroy_all"
    resources :contacts, only: [:index, :destroy, :show, :update]
  end

  #get '*path', controller: 'application', action: 'render_404'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/photo.rb
class Photo < ApplicationRecord
	default_scope -> { order(created_at: :desc)}
  enum range: { 全ユーザー: 0, フォロワーのみ: 1, 自分のみ: 2 }

  validates :image, presence: { message: "を選択してください"}
  validates :word, presence: true, length: { maximum: 140}
  validates :range, presence: { message: "を選択してください"}

	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy
	def liked_by?(user)
		likes.where(user_id: user.id).exists?
	end

  has_many :notifications, dependent: :destroy
  # いいね通知
  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and photo_id = ? and action = ?", current_user.id, user_id, id, 0])
    # いいねされてない場合のみ通知
    if temp.blank?
      notification = current_user.active_notifications.new(
        photo_id: id,
        visited_id: user_id,
        action: 'like'
      )
      notification.save if notification.valid?
    end
  end

  # コメント通知
  def create_notification_comment!(current_user, comment_id)
    notification = current_user.active_notifications.new(
      photo_id: id,
      comment_id: comment_id,
      visited_id: user_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントは通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end


  attachment :image

  acts_as_taggable #タグ付け
  is_impressionable counter_cache: true #閲覧数
end

app/controllers/admins/photos_controller.rb
class Admins::PhotosController < ApplicationController
  before_action :authenticate_admin!
  def index
    @photos = Photo.page(params[:page]).per(24)
    @name = "投稿一覧"
    if params[:tag_name]
      @photos = Photo.tagged_with("#{params[:tag_name]}").page(params[:page]).per(24)
      @name = "”#{params[:tag_name]}”一覧"
    elsif params[:created_at]
      @photos = Photo.where(created_at: Time.zone.now.all_day).page(params[:page]).per(24)
      @name = "本日の新規投稿一覧"
    end
  end

  def show
    @photo = Photo.find(params[:id])
    @user = User.find(@photo.user_id)
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to admins_photos_path
  end
end

app/controllers/users/photos_controller.rb
class Users::PhotosController < ApplicationController
  before_action :authenticate_user!

  impressionist :actions => [:show], :unique => [:impressionable_id, :user_id]

  def index
    @user = User.find(current_user.id)
    @array = []

    if params[:tag_name]
      @photos = Photo.tagged_with("#{params[:tag_name]}")
      @name = "”#{params[:tag_name]}”一覧"
    elsif params[:follow]
      @photos = Photo.where(user_id: current_user.following_user)
      @name = "投稿一覧"
    else
      @photos = Photo.all
      @name = "投稿一覧"
    end

    #ページネーションが上手くいかなかったため、配列取り出し
    @photos.each do |photo|
      if photo.range == "全ユーザー"
        @array.push(photo)
      elsif photo.range == "フォロワーのみ"
        if current_user.following?(photo.user) || photo.user.id == current_user.id
          @array.push(photo)
        end
      else
        if photo.user.id == current_user.id
          @array.push(photo)
        end
      end
    end

    @photos_array = Kaminari.paginate_array(@array).page(params[:page]).per(12)
  end

  def new
  	@photo = Photo.new
  end

  def create
  	@photo = Photo.new(photo_params)
  	@photo.user_id = current_user.id
  	if @photo.save
        redirect_to photo_path(@photo.id)
    else
      render 'new'
    end
  end

  def show
    @photo = Photo.find(params[:id])
    @user = User.find(@photo.user_id)
    @comment = Comment.new
  end

  def update
    @photo = Photo.find(params[:id])
    @photo.update(photo_params)
    redirect_to photo_path(params[:id])
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to user_path(current_user)
  end

  def likes
    @photo = Photo.find(params[:id])
    @likes = Like.where(photo_id: @photo.id).page(params[:page]).per(10)
  end

  def comments
    @photo = Photo.find(params[:id])
    @comments = Comment.where(photo_id: @photo.id).page(params[:page]).per(10)
  end


  private
  def photo_params
  	params.require(:photo).permit(:user_id, :image, :word, :range, :tag_list)
  end
end

app/helpers/admins/photos_helper.rb
module Admins::PhotosHelper
end

app/helpers/users/photos_helper.rb
module Users::PhotosHelper
end

app/views/admins/photos/index.html.erb
<div class="row d-inline-block" style="padding: 0 10px;">
  <div class="col-md-12 title">
    <h3><%= @name %></h3>
  </div>
</div>

<div class="row">
  <div class="col-12 photo">
    <% @photos.each do |photo| %>
      <%= link_to admins_photo_path(photo.id), style: "color: black;" do %>
        <div class="col-sm-12 col-md-6 col-lg-4 col-xl-3 float-left frame">
          <div class="picture" style="margin: auto;">
            <div class="row">
              <div class="col-12">
                <%= attachment_image_tag photo, :image, :fill, 300, 300 %>
              </div>
            </div>
            <div class="row" style="margin-top: 3px;">
              <div class="col-12 over-text">
                <%= l photo.created_at %>　<%= photo.word %>
              </div>
            </div>
            <div class="row">
              <div class="col-4" style="text-align: left; padding-left: 10%;">
                <i class="far fa-heart">:<%= photo.likes.count %></i>
              </div>
              <div class="col-4" style="text-align: center;">
                <i class="far fa-comments">:<%= photo.comments.count %></i>
              </div>
              <div class="col-4" style="text-align: right; padding-right: 10%;">
                <i class="far fa-eye">:<%= photo.impressions_count %></i>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
    <div style="clear: both;">
      <%= paginate @photos %>
    </div>
  </div>
</div>

app/views/admins/photos/show.html.erb
<div class="row d-inline-block" style="padding: 0 10px;">
  <div class="col-md-12 title">
    <h3>投稿詳細</h3>
  </div>
</div>

<div class="row" style="max-width: 992px; margin: 15px auto;">
  <div class="col-md-6">
    <div class="show_box" style="font-size: 14px;">
      <%= link_to admins_user_path(@user), style: "color: black; text-decoration: none;" do %>
        <div class="row" style="width: 95%; border-bottom: solid 1px gray; margin: auto; padding: 10px 0;">
          <div class="col-3" style="max-width: 70px;">
            <%= attachment_image_tag @user, :image, :fill, 100, 100, fallback: 'no_image.jpg', size: '100x100', style: "border-radius: 50%;" %>
          </div>
          <div class="col-9 over-text" style="margin: auto 0;">
            <%= "#{@user.last_name} #{@user.first_name}" %>
          </div>
        </div>
      <% end %>
      <div class="row" style="margin: 15px auto;">
        <div class="col-12">
          <%= attachment_image_tag @photo, :image, class: "picture_stop" %>
        </div>
      </div>
      <div class="row" style="margin: auto; font-size: 11px;">
        <div class="col-12">
          <%= l @photo.created_at %>
        </div>
      </div>
      <div class="row" style="margin: auto; padding-top: 1px; padding-bottom: 20px;">
        <div class="col-12">
          <%= simple_format(@photo.word) %>
        </div>
      </div>
      <div class="row" style="margin: auto;">
        <div class="col-12">
          <span>タグ <i class="far fa-hand-point-right"></i></span>
            <% @photo.tag_list.each do |tag| %>
              <%= link_to admins_photos_path(tag_name: tag), class: "text-white btn btn-info btn-sm p-0 m-1" do %>
                <%= tag %>
              <% end %>
            <% end %>
        </div>
      </div>
      <div class="row" style="padding: 5px 0; border-top: solid 1px gray; margin: auto; width: 95%;">
        <div class="col-4" style="text-align: center;">
          <i class="far fa-heart">:<%= @photo.likes.count %></i>
        </div>
        <div class="col-4" style="text-align: center;">
          <i class="far fa-comments">:<%= @photo.comments.count %></i>
        </div>
        <div class="col-4" style="text-align: center;">
          <i class="far fa-eye">:<%= @photo.impressions_count %></i>
        </div>
      </div>
        <div class="row">
          <div class="col-12" style="text-align: center;">
            <%= link_to '投稿削除', admins_photo_path(@photo), method: :delete, "data-confirm" => "投稿を削除します。よろしいですか？", class: "btn btn-danger", style: "margin: 10px 0;" %>
          </div>
        </div>
    </div>
  </div>
</div>