config/routes.rb
Rails.application.routes.draw do

  root 'users/homes#top'
  devise_for :users, only: [:session, :registration]
  devise_for :admins, only: :session

  scope module: :users do
    delete "notifications" => "notifications#destroy_all"
    resources :notifications, only: [:index, :destroy]
    get 'homes/about'
    resources :users, only: [:show, :edit, :update, :destroy] do
      post 'follow/:id' => 'relationships#follow', as: 'follow'
      post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
      member do
        get :retire, :follow, :follower
      end
    end
    resources :photos, only: [:index, :new, :create, :show, :destroy, :update] do
      member do
        get :likes, :comments
      end
      resources :comments, only: [:create, :destroy, :update]
      resource :likes, only: [:create, :destroy]
    end
    resource :contacts, only: [:new, :create]
    get 'contacts/done' => "contacts#done"
  end


  namespace :admins do
    get 'home/top'
    resources :users, only: [:index, :show, :destroy]
    resources :photos, only: [:index, :show, :destroy]
    delete "contacts" => "contacts#destroy_all"
    resources :contacts, only: [:index, :destroy, :show, :update]
  end

  #get '*path', controller: 'application', action: 'render_404'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admins/home_controller.rb
class Admins::HomeController < ApplicationController
  before_action :authenticate_admin!

  def top
    @users = User.all
    @users_today = User.where(created_at: Time.zone.now.all_day)
    @photos = Photo.all
    @photos_today = Photo.where(created_at: Time.zone.now.all_day)
    @contacts = Contact.where(status: "未対応")
  end
end

app/controllers/users/homes_controller.rb
class Users::HomesController < ApplicationController
  def about
  end

  def top
  end
end

app/helpers/admins/home_helper.rb
module Admins::HomeHelper
end

app/helpers/users/homes_helper.rb
module Users::HomesHelper
end

app/views/admins/home/top.html.erb
<div class="row" style="padding: 20px 0 0 20px;">
  <div class="col-12">
    <h4 style="font-size: 35px;">Topページ</h4>
  </div>
  <div class="col-12" style="font-size: 20px;">
    <ul>
      <li>
        全ユーザー数
        <%= link_to admins_users_path do %>
          <%= @users.count %> 人
        <% end %>
      </li>
      <li>
        本日の新規ユーザー数
        <%= link_to admins_users_path(created_at: Time.zone.now.all_day) do %>
          <%= @users_today.count %> 人
        <% end %>
      </li>
      <li>
        全投稿件数
        <%= link_to admins_photos_path do %>
          <%= @photos.count %> 件
        <% end %>
      </li>
      <li>
        本日の投稿件数
        <%= link_to admins_photos_path(created_at: Time.zone.now.all_day) do %>
          <%= @photos_today.count %>
        <% end %>
      </li>
      <li>
        未対応お問い合わせ件数
        <%= link_to admins_contacts_path do %>
          <%= @contacts.count %> 件
        <% end %>
      </li>
    </ul>
  </div>
</div>