config/routes.rb
Rails.application.routes.draw do

  root 'users/homes#top'
  devise_for :users, only: [:session, :registration]
  devise_for :admins, only: :session

  scope module: :users do
    delete "notifications" => "notifications#destroy_all"
    resources :notifications, only: [:index, :destroy]
    get 'homes/about'
    resources :users, only: [:show, :edit, :update, :destroy] do
      post 'follow/:id' => 'relationships#follow', as: 'follow'
      post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
      member do
        get :retire, :follow, :follower
      end
    end
    resources :photos, only: [:index, :new, :create, :show, :destroy, :update] do
      member do
        get :likes, :comments
      end
      resources :comments, only: [:create, :destroy, :update]
      resource :likes, only: [:create, :destroy]
    end
    resource :contacts, only: [:new, :create]
    get 'contacts/done' => "contacts#done"
  end


  namespace :admins do
    get 'home/top'
    resources :users, only: [:index, :show, :destroy]
    resources :photos, only: [:index, :show, :destroy]
    delete "contacts" => "contacts#destroy_all"
    resources :contacts, only: [:index, :destroy, :show, :update]
  end

  #get '*path', controller: 'application', action: 'render_404'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/photo.rb
class Photo < ApplicationRecord
	default_scope -> { order(created_at: :desc)}
  enum range: { 全ユーザー: 0, フォロワーのみ: 1, 自分のみ: 2 }

  validates :image, presence: { message: "を選択してください"}
  validates :word, presence: true, length: { maximum: 140}
  validates :range, presence: { message: "を選択してください"}

	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy
	def liked_by?(user)
		likes.where(user_id: user.id).exists?
	end

  has_many :notifications, dependent: :destroy
  # いいね通知
  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and photo_id = ? and action = ?", current_user.id, user_id, id, 0])
    # いいねされてない場合のみ通知
    if temp.blank?
      notification = current_user.active_notifications.new(
        photo_id: id,
        visited_id: user_id,
        action: 'like'
      )
      notification.save if notification.valid?
    end
  end

  # コメント通知
  def create_notification_comment!(current_user, comment_id)
    notification = current_user.active_notifications.new(
      photo_id: id,
      comment_id: comment_id,
      visited_id: user_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントは通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end


  attachment :image

  acts_as_taggable #タグ付け
  is_impressionable counter_cache: true #閲覧数
end

app/controllers/admins/photos_controller.rb
class Admins::PhotosController < ApplicationController
  before_action :authenticate_admin!
  def index
    @photos = Photo.page(params[:page]).per(24)
    @name = "投稿一覧"
    if params[:tag_name]
      @photos = Photo.tagged_with("#{params[:tag_name]}").page(params[:page]).per(24)
      @name = "”#{params[:tag_name]}”一覧"
    elsif params[:created_at]
      @photos = Photo.where(created_at: Time.zone.now.all_day).page(params[:page]).per(24)
      @name = "本日の新規投稿一覧"
    end
  end

  def show
    @photo = Photo.find(params[:id])
    @user = User.find(@photo.user_id)
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to admins_photos_path
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page]).per(10)
    @name = ""
    if params[:created_at]
      @users = User.where(created_at: Time.zone.now.all_day).page(params[:page]).per(10)
      @name = "本日の新規登録"
    end
  end

  def show
    @user = User.find(params[:id])
    @photos = Photo.where(user_id: params[:id]).page(params[:page]).per(24)
    @name = "#{@user.last_name}#{@user.first_name}さん"
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admins_users_path
  end
end

app/controllers/users/comments_controller.rb
class Users::CommentsController < ApplicationController

  def create
    @photo = Photo.find(params[:photo_id])
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.photo_id = @photo.id
    if @comment.save
      @photo.create_notification_comment!(current_user, @comment.id)
      redirect_to photo_comments_path
    else
      @user = User.find(@photo.user_id)
      render 'users/photos/show'
    end
  end

  def destroy
    @comment = Comment.find_by(photo_id: params[:photo_id], id: params[:id])
    @comment.destroy
    redirect_to photo_comments_path
  end

  def update
    @comment = Comment.find_by(photo_id: params[:photo_id], id: params[:id])
    @comment.update_attributes(thanks: params[:thanks])
    @comment.create_notification_thanks!(current_user)
  end


  private
  def comment_params
    params.require(:comment).permit(:comment, :thanks)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/contacts_controller.rb
class Users::ContactsController < ApplicationController
  before_action :authenticate_user!

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to action: :done
    else
      render 'new'
    end
  end

  def done
  end


  private

  def contact_params
    params.require(:contact).permit(:user_id, :title, :content, :status)
  end
end

app/controllers/users/homes_controller.rb
class Users::HomesController < ApplicationController
  def about
  end

  def top
  end
end

app/controllers/users/likes_controller.rb
class Users::LikesController < ApplicationController

  def create
    @photo = Photo.find(params[:photo_id])
    @like = current_user.likes.new(photo_id: @photo.id)
    @like.save
    @photo.create_notification_like!(current_user)
  end

  def destroy
    @photo = Photo.find(params[:photo_id])
    @like = current_user.likes.find_by(photo_id: @photo.id)
    @like.destroy
  end
end

app/controllers/users/notifications_controller.rb
class Users::NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(10)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end

  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy
    redirect_to notifications_path
  end

  def destroy_all
    @notifications = current_user.passive_notifications.destroy_all
    redirect_to notifications_path
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/photos_controller.rb
class Users::PhotosController < ApplicationController
  before_action :authenticate_user!

  impressionist :actions => [:show], :unique => [:impressionable_id, :user_id]

  def index
    @user = User.find(current_user.id)
    @array = []

    if params[:tag_name]
      @photos = Photo.tagged_with("#{params[:tag_name]}")
      @name = "”#{params[:tag_name]}”一覧"
    elsif params[:follow]
      @photos = Photo.where(user_id: current_user.following_user)
      @name = "投稿一覧"
    else
      @photos = Photo.all
      @name = "投稿一覧"
    end

    #ページネーションが上手くいかなかったため、配列取り出し
    @photos.each do |photo|
      if photo.range == "全ユーザー"
        @array.push(photo)
      elsif photo.range == "フォロワーのみ"
        if current_user.following?(photo.user) || photo.user.id == current_user.id
          @array.push(photo)
        end
      else
        if photo.user.id == current_user.id
          @array.push(photo)
        end
      end
    end

    @photos_array = Kaminari.paginate_array(@array).page(params[:page]).per(12)
  end

  def new
  	@photo = Photo.new
  end

  def create
  	@photo = Photo.new(photo_params)
  	@photo.user_id = current_user.id
  	if @photo.save
        redirect_to photo_path(@photo.id)
    else
      render 'new'
    end
  end

  def show
    @photo = Photo.find(params[:id])
    @user = User.find(@photo.user_id)
    @comment = Comment.new
  end

  def update
    @photo = Photo.find(params[:id])
    @photo.update(photo_params)
    redirect_to photo_path(params[:id])
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to user_path(current_user)
  end

  def likes
    @photo = Photo.find(params[:id])
    @likes = Like.where(photo_id: @photo.id).page(params[:page]).per(10)
  end

  def comments
    @photo = Photo.find(params[:id])
    @comments = Comment.where(photo_id: @photo.id).page(params[:page]).per(10)
  end


  private
  def photo_params
  	params.require(:photo).permit(:user_id, :image, :word, :range, :tag_list)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/relationships_controller.rb
class Users::RelationshipsController < ApplicationController

  def follow
    @user = User.find(params[:user_id])
    current_user.follow(params[:user_id])
    @user.create_notification_follow!(current_user)
  end

  def unfollow
    @user = User.find(params[:user_id])
    current_user.unfollow(params[:user_id])
  end


  private

  def relationship_params
    params.require(:relationship).permit(:user_id)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :retire]

  def show
    @user = User.find(params[:id])
    @array = []
    @photos = Photo.where(user_id: params[:id])

    if @user == current_user
      @name = "あなた"
    else
      @name = "#{@user.last_name}#{@user.first_name}さん"
    end

    @photos.each do |photo|
      if photo.range == "全ユーザー"
        @array.push(photo)
      elsif photo.range == "フォロワーのみ"
        if current_user.following?(photo.user) || photo.user.id == current_user.id
          @array.push(photo)
        end
      else
        if photo.user.id == current_user.id
          @array.push(photo)
        end
      end
    end

    @photos_array = Kaminari.paginate_array(@array).page(params[:page]).per(12)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(params[:id])
    else
      render "edit"
    end
  end

  def retire
  end

  def destroy
    @user = User.find(current_user.id)
    @user.destroy
    redirect_to root_path
  end

  def follow
    @user = User.find(params[:id])
    @users = @user.following_user.page(params[:page]).per(10)
  end

  def follower
    @user = User.find(params[:id])
    @users = @user.follower_user.page(params[:page]).per(10)
  end



  private
  def user_params
    params.require(:user).permit(:image, :last_name, :first_name, :read_last_name, :read_first_name, :email, :introduction)
  end

  def correct_user
    if current_user != User.find(params[:id])
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/admins/photos_helper.rb
module Admins::PhotosHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/views/users/photos/_photo.html.erb
<%= link_to photo_path(photo.id), style: "color: black;" do %>
  <div class="col-sm-6 col-md-12 col-lg-6 clo-xl-4 float-left frame">
    <div clas="picture" style="margin: auto;">
      <div class="row">
        <div class="col-12">
          <%= attachment_image_tag photo, :image, :fill, 300, 300, id: 'rspec_photo' %>
        </div>
      </div>
      <div class="row" style="margin-top: 3px;">
        <div class="col-12 over-text">
          <%= l photo.created_at %>  <%= photo.word %>
        </div>
      </div>
      <div class="row">
        <div class="col-4" style="text-align: left; padding-left: 10%;">
          <i class="far fa-heart">:<%= photo.likes.count %></i>
        </div>
        <div class="col-4" style="text-align: center;">
          <i class="far fa-comments">:<%= photo.comments.count %></i>
        </div>
        <div class="col-4" style="text-align: right; padding-right: 10%;">
          <i class="far fa-eye">:<%= photo.impressions_count %></i>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/photos/comments.html.erb
<div class="row d-inline-block" style="padding: 0 10px;">
    <div class="col-md-12 title">
        <h3>コメントしたユーザー一覧</h3>
    </div>
</div>
<div class="row">
    <div class="col-12" style="padding-left: 20px padding-bottom: 5px;">
        <h5><%= link_to :back, style: "color: black;" do %>
        <i class="far fa-hand-point-left">投稿へ戻る</i></h5>
        <% end %>
    </div>
</div>

<% @comments.each do |comment| %>
  <div class="row box" style="max-width: 768px; font-size: 13px; margin-bottom: 5px;">
      <div class="col-2" style="margin-top: 5px; max-width: 80px;">
          <%= link_to user_path(comment.user) do %>
            <%= attachment_image_tag comment.user, :image, :fill, 100, 100, fallback: 'no_image.jpg', size: '100x100', style: "border-radius: 50%;" %>
          <% end %>
      </div>
      <div class="col-10">
          <div class="row" style="margin-top: 3px;">
              <div class="col-5 col-sm-6 col-md-7 over-text" style="margin: auto 0;">
                  <%= link_to user_path(comment.user), style: "color: black; text-decoration: none;" do %>
                    <%= "#{comment.user.last_name} #{comment.user.first_name}" %>
                  <% end %>
              </div>
              <div class="col-5 col-sm-4 col-md-3" style="margin: auto 0;">
                  <% if comment.user.id != current_user.id %>
                    <% @user = comment.user %>
                    <div class="follows_buttons_<%= @user.id %>">
                        <%= render partial: 'users/relationships/follow_button', locals: { user: @user } %>
                    </div>
                  <% else %>
                    <%= link_to "コメント削除", photo_comment_path(@photo, comment), class: "btn btn-sm btn-danger bagde-pill", style: "width: 120px;", method: :delete, "data-confirm" => "コメントを削除します。よろしいですか？" %>
                  <% end %>
              </div>
              <div class="col-2" style="margin: auto 0;">
                  <div class="comments_thanks_<%= comment.id %>">
                      <%= render partial: 'users/comments/thanks', locals: { photo: @photo, comment: comment } %>
                  </div>
              </div>
          </div>
          <div class="row">
              <div class="col-12">
                  <%= simple_format(comment.comment) %>
              </div>
          </div>
      </div>
  </div>
<% end %>

<%= paginate @comments %>

app/views/users/photos/index.html.erb
<div class="row d-inline-block" style="padding: 0 10px;">
  <div class="col-md-12 title">
    <h3><%= @name %></h3>
  </div>
</div>

<div class="row">
  <div class="col-md-5 col-lg-4 col-xl-3">
    <div class="row">
      <div class="col-12" style="text-align: right; margin-top: 5px;">
        <% if params[:follow] == nil %>
          <div class="btn btn-group-sm" role="group" aria-label="...">
            <%= link_to "全ユーザー", photos_path, class: "btn btn-success btn-sm active p-1 m-0" %>
            <%= link_to "フォロー", photos_path(follow: :follow), class: "btn btn-outline-success btn-sm p-1 m-0" %>
          </div>
        <% else %>
          <div class="btn-group btn-group-sm" role="group" aria-label="...">
            <%= link_to "全ユーザー", photos_path, class: "btn btn-outline-success btn-sm p-1 m-0" %>
            <%= link_to "フォロー", photos_path(follow: :follow), class: "btn btn-success btn-sm active p-1 m-0" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="sidebar_fixed side">
      <span class="side_title">プロフィール</span>
      <div class="row" style="margin: 10px 0;">
        <div class="col-12" style="text-align: center;">
          <% if @user.image.nil? %>
            <%= attachment_image_tag @user, :image, :fill, 200, 200, fallback: 'no_image.jpg', size: '300x200', class: "radius" %>
          <% else %>
            <%= link_to attachment_url(@user, :image), :rel => "lightbox" do %>
              <%= attachment_image_tag @user, :image, :fill, 200, 200, fallback: 'no_image.jpg', size: '300x200', class: "radius" %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-12 over-text" style="text-align: center;">
          <strong>
            <%= "#{@user.last_name} #{@user.first_name}" %>　<%= "(#{@user.read_last_name} #{@user.read_first_name})" %>
          </strong>
        </div>
      </div>
      <div class="row" style="margin: 10px 0;">
        <div class="col-12" style="height: auto;">
          <h6><%= simple_format(@user.introduction) %></h6>
        </div>
      </div>
      <div class="row" style="padding: 5px 0; margin: auto; width: 90%; border-top: solid 1px gray;">
        <div class="col-6" style="text-align: center;">
          <%= link_to follow_user_path(id: current_user.id), style: "color: black; text-decoration: none;" do %>
            <%= @user.follower.count %><span style="font-size: 10px;"> フォロー</span>
          <% end %>
        </div>
        <div class="col-6" style="text-align: center;">
          <%= link_to follower_user_path(id: current_user.id), style: "color: black; text-decoration none;" do %>
            <%= @user.followed.count %><span style="font-size: 10px;"> フォロワー</span>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-12" style="text-align: right; margin: 10px 0; padding-right: 10%;">
          <%= link_to edit_user_path(current_user), style: "text-decoration: none; color: gray;" do %>
            <i class="fas fa-wrench"> 編集</i>
          <% end %>
          <%= link_to notifications_path, style: "margin-left: 30px;" do %>
            <% if notifications_count > 0 %>
              <span class="fa-stack">
                <i class="fas fa-bell fa-stack-2x"></i>
                <span class="fa-stack fa-stack-1x counter"><%= @notifications %></span>
              </span>
            <% else %>
              <span class="fa-stack">
                <i class="fas fa-bell fa-stack-2x"></i>
              </span>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-7 col-lg-8 col-xl-9 photo">
    <% @photos_array.each do |photo| %>
      <%= render partial: 'users/photos/photo', locals: { photo: photo } %>
    <% end %>
    <div style="clear: both;">
      <%= paginate @photos_array %>
    </div>
  </div>
</div>

app/views/users/photos/show.html.erb
<div class="row d-inline-block" style="padding: 0 10px;">
    <div class="col-md-12 title">
        <h3>投稿詳細</h3>
    </div>
</div>

<div class="row">
    <div class="col-12" style="max-width: 992px; margin: auto;">
        <%= render "users/shared/error_messages", resource: @comment %>
    </div>
</div>

<div class="row" style="max-width: 992px; margin: 15px auto;">
    <div class="col-md-6">
        <div class="show_box" style="font-size: 14px;">
            <%= link_to user_path(@user), style: "color: black; text-decoration: none;" do %>
              <div class="row" style="width: 95%; border-bottom: solid 1px gray; margin: auto; padding: 10px 0;">
                  <div class="col-3" style="max-width: 70px;">
                      <%= attachment_image_tag @user, :image, :fill, 100, 100, fallback: 'no_image.jpg', size: '100x100', style: "border-radius 50%;" %>
                  </div>
                  <div class="col-9 over-text" style="margin: auto 0;">
                      <%= "#{@user.last_name} #{@user.first_name}" %>
                  </div>
              </div>
            <% end %>
            <div class="row" style="margin: 15px auto;">
                <div class="col-12">
                    <%= link_to attachment_url(@photo, :image), :rel => "lightbox" do %>
                      <%= attachment_image_tag @photo, :image, class: "picture_stop", id: 'rspec_photo' %>
                    <% end %>
                </div>
            </div>
            <div class="row" style="margin: auto; font-size: 11px;">
                <div class="col-12">
                    <%= l @photo.created_at %>
                </div>
            </div>
            <div class="row" style="margin: auto; padding-top: 1px; padding-bottom: 20px">
                <div class="col-12">
                    <%= simple_format(@photo.word) %>
                </div>
            </div>
            <div class="row" style="margin: auto;">
                <div class="col">
                    <span>タグ <i class="far fa-hand-point-right"></i></span>
                      <% @photo.tag_list.each do |tag| %>
                        <%= link_to photos_path(tag_name: tag), class: "text-white btn btn-info btn-sm p-o m-1" do %>
                          <%= tag %>
                        <% end %>
                      <% end %>
                </div>
            </div>
            <div class="row" style="padding: 5px 0; border-top: solid 1px gray; margin:auto; width: 95%;">
                <div class="col-3" style="text-align: center;">
                    <div class="likes_counts_<%= @photo.id %>">
                        <%= render partial: 'users/likes/like_counts', locals: { photo: @photo } %>
                    </div>
                </div>
                <div class="col-3" style="text-align: center;">
                    <%= link_to photo_comments_path(@photo), style: "color: black;" do %>
                      <i class="far fa-comments">:<%= @photo.comments.count %></i>
                    <% end %>
                </div>
                <div class="col-3" style="text-align: center;">
                    <i class="far fa-eye">:<%= @photo.impressions_count %></i>
                </div>
                <div class="col-3" style="text-align: center;">
                    <% if @user == current_user %>
                      <%= link_to photo_path(@photo), style: "color: gray;", method: :delete, "data-confirm" => "投稿を削除します。よろしいですか？", id: "rspec_delete" do %>
                        <i class="far fa-trash-alt"></i>
                      <% end %>
                    <% else %>
                      <div class="likes_buttons_<%= @photo.id %>">
                          <%= render partial: 'users/likes/like', locals: { photo: @photo } %>
                      </div>
                    <% end %>
                </div>
            </div>
            <% if @user == current_user %>
              <%= form_with model: @photo, local: true do |f| %>
                <%= f.hidden_field :user_id, :value => @photo.user_id %>
                <%= f.hidden_field :image, :value => @photo.image %>
                <%= f.hidden_field :word, :value => @photo.word %>
                <div class="row" style="width: 90%; margin: 15px auto;">
                    <div class="col-8">
                        <%= f.select :range, [["全ユーザー", "全ユーザー"], ["フォロワーのみ", "フォロワーのみ"], ["自分のみ", "自分のみ"]], {}, {class: "form-control", style: "width: 100%;"} %>
                    </div>
                    <div class="col-4">
                        <%= f.submit '更新', class: "btn btn-primary", style: "width: 100%" %>
                    </div>
                </div>
              <% end %>
            <% end %>
        </div>
    </div>

    <div class="col-md-6 align-self-end">
        <%= form_with(model: [@photo, @comment], local: true) do |f| %>
          <div class="form-row d-flex align-items-end">
              <div class="col-12">
                  <%= f.text_area :comment, placeholder: "コメント", class: "form-control", id: "input-text", rows: "4" %>
                  <p style="text-align: right; padding-bottom: 0;" id="counter">140文字まで</p>
              </div>
          </div>
          <div class="form-row" style="margin-top: 0;">
              <div class="col-12">
                  <%= f.submit 'コメントする', class: "btn btn-primary", style: "width: 100%;" %>
              </div>
          </div>
        <% end %>
    </div>
</div>

<script type="text/javascript">
  $(function(){
  $("#input-text").on("keyup", function() {
    let countNum = String($(this).val().length);
    if(countNum>50){
      $("#counter").text(countNum + "/50").css("color", "red");
    }else {
      $("#counter").text(countNum + "/50").css("color", "");
    }
 });
});
</script>