config/routes.rb
Rails.application.routes.draw do

  root 'users/homes#top'
  devise_for :users, only: [:session, :registration]
  devise_for :admins, only: :session

  scope module: :users do
    delete "notifications" => "notifications#destroy_all"
    resources :notifications, only: [:index, :destroy]
    get 'homes/about'
    resources :users, only: [:show, :edit, :update, :destroy] do
      post 'follow/:id' => 'relationships#follow', as: 'follow'
      post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
      member do
        get :retire, :follow, :follower
      end
    end
    resources :photos, only: [:index, :new, :create, :show, :destroy, :update] do
      member do
        get :likes, :comments
      end
      resources :comments, only: [:create, :destroy, :update]
      resource :likes, only: [:create, :destroy]
    end
    resource :contacts, only: [:new, :create]
    get 'contacts/done' => "contacts#done"
  end


  namespace :admins do
    get 'home/top'
    resources :users, only: [:index, :show, :destroy]
    resources :photos, only: [:index, :show, :destroy]
    delete "contacts" => "contacts#destroy_all"
    resources :contacts, only: [:index, :destroy, :show, :update]
  end

  #get '*path', controller: 'application', action: 'render_404'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
  default_scope -> { order(created_at: :desc)}
	enum status: { 未対応: false, 対応済: true }

  validates :title, presence: true, length: { maximum: 50}
  validates :content, presence: true, length: { maximum: 150}

	belongs_to :user
end

app/controllers/admins/contacts_controller.rb
class Admins::ContactsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @contacts = Contact.page(params[:page]).per(10)
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    @contact.update_attributes(status: contact_params[:status])
    redirect_to admins_contacts_path
  end

  def destroy
    @contacts = Contact.find(params[:id])
    @contacts.destroy
    redirect_to admins_contacts_path
  end


  def contact_params
    params.require(:contact).permit(:user_id, :title, :content, :status)
  end

end

app/controllers/users/contacts_controller.rb
class Users::ContactsController < ApplicationController
  before_action :authenticate_user!

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to action: :done
    else
      render 'new'
    end
  end

  def done
  end


  private

  def contact_params
    params.require(:contact).permit(:user_id, :title, :content, :status)
  end
end

app/helpers/admins/contact_helper.rb
module Admins::ContactHelper
end

app/helpers/users/contacts_helper.rb
module Users::ContactsHelper
end

app/views/admins/contacts/index.html.erb
<div class="row d-inline-block" style="padding: 0 10px;">
  <div class="col-md-12 title">
    <h3>お問い合わせ一覧</h3>
  </div>
</div>

<table class="table table-sm" style="max-width: 768px; margin: auto;">
  <thead>
    <tr class="table-success">
      <th style="width:10%;"></th>
      <th style="width: 10%;">日付</th>
      <th style="width: 25%;">氏名</th>
      <th style="width: 30%;">件名</th>
      <th style="width: 15%;"></th>
    </tr>
  </thead>
  <% @contacts.each do |contact| %>
    <tbody>
      <tr>
        <td style="text-align: center;">
          <% if contact.status == "対応済" %>
            <i class="fas fa-check" style="color: green;"></i>
          <% end %>
        </td>
        <td><%= l contact.created_at, format: :short %></td>
        <td class="over-text" style="max-width: 0;">
          <%= link_to admins_user_path(contact.user), style: "color: black; text-decoration: none;" do %>
            <%= "#{contact.user.last_name} #{contact.user.first_name}" %>
          <% end %>
        </td>
        <td class="over-text" style="max-width: 0;">
          <%= link_to admins_contact_path(contact) do %>
            <%= contact.title %>
          <% end %>
        </td>
        <td><%= link_to "削除", admins_contact_path(contact), class: "btn btn-sm btn-danger", method: :delete, "data-confirm" => "お問い合わせを削除します。よろしいですか？" %></td>
      </tr>
    </tbody>
  <% end %>
</table>

<%= paginate @contacts %>

app/views/admins/contacts/show.html.erb
<div class="row d-inline-block" style="padding: 0 10px;">
  <div class="col-md-12 title">
    <h3>お問い合わせ詳細</h3>
  </div>
</div>

<div class="row" style="max-width: 575px; margin: auto;">
  <table class="table contact_box" style="background-color: ivory;">
    <tr>
      <th style="width: 45%;">氏名</th>
      <td style="width: 55%; max-width: 0;" class="over-text">
        <%= link_to admins_user_path(@contact.user), style: "color: black; text-decoration: none;" do %>
          <%= "#{@contact.user.last_name} #{@contact.user.first_name} (#{@contact.user.read_last_name} #{@contact.user.read_first_name})" %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td style="max-width: 0;" class="over-text"><%= mail_to "#{@contact.user.email}" %></td>
    </tr>
    <tr>
      <th>日時</th>
      <td><%= l @contact.created_at, format: :long %></td>
    </tr>
    <tr>
      <th>件名</th>
      <td><%= @contact.title %></td>
    </tr>
    <tr>
      <th>内容</th>
      <td><%= simple_format(@contact.content) %></td>
    </tr>
  </table>
</div>

<%= form_with model: [:admins, @contact], local: true do |f| %>
<div class="row" style="max-width: 575px; margin: 20px auto;">
  <div class="col-6">
    <%= f.select :status, [["未対応","未対応"],["対応済","対応済"]], {}, {class: "form-control", style: "width: 100%;"} %>
  </div>
  <div class="col-3">
    <%= f.submit '更新', class: "btn btn-primary", style: "width: 100%;" %>
  </div>
  <div class="col-3">
    <%= link_to "削除", admins_contact_path(@contact), class: "btn btn-danger", style: "width: 100%;", method: :delete, "data-confirm" => "お問い合わせを削除します。よろしいですか？" %>
  </div>
</div>
<% end %>